project:
  type: book
  output-dir: _book

book:
  title: "Introduction to Programming Using Go"
  author: "Gongbing Hong"
  date: "2026-03-25"
  
  # This sets up your sidebar navigation with Parts and Chapters
  chapters:
    - index.qmd
    - part: "Getting Started"
      chapters:
        #- part1-getting-started/index.qmd       
        - part1-getting-started/ch01-the-basics.qmd
        - part1-getting-started/ch02-data-types-computation.qmd
    - part: "Control Structures"
      chapters:
        #- part2-control-structures/index.qmd
        - part2-control-structures/ch03-conditionals.qmd
        - part2-control-structures/ch04-loops.qmd
    - part: "Modular Programming"
      chapters:
        #- part3-modular-programming/index.qmd
        - part3-modular-programming/ch05-functions.qmd
        - part3-modular-programming/ch06-modules-packages.qmd
        - part3-modular-programming/ch07-testing-debugging.qmd
        - part3-modular-programming/ch08-data-structures-algos.qmd
    - part: "Advanced Topics"
      chapters:
        - part4-advanced-topics/ch09-methods-interfaces.qmd
        - part4-advanced-topics/ch10-generics-type-parameters.qmd
        - part4-advanced-topics/ch11-file-io.qmd
        - part4-advanced-topics/ch12-concurrency.qmd
        - part4-advanced-topics/ch13-net-programming.qmd
        - part4-advanced-topics/ch14-web-programming.qmd
        - part4-advanced-topics/ch15-programming-security.qmd
    - references.qmd

format:
  html:
    theme: cosmo
    toc: true               # Table of contents for each page
    code-copy: true         # Handy "Copy" button on Go code snippets
  pdf:
    documentclass: scrreprt # Excellent for academic printing
