project:
  type: book
  output-dir: _book

book:
  title: "Introduction to Programming Using Go"
  author: "Gongbing Hong"
  date: "2026-03-25"
  
  # This sets up your sidebar navigation with Parts and Chapters
  chapters:
    - index.qmd
    - part: "Getting Started"
      chapters:
        #- part1-getting-started/index.qmd       
        - part1-getting-started/ch01-the-basics.qmd
        - part1-getting-started/ch02-data-types-computation.qmd
    - part: "Control Structures"
      chapters:
        #- part2-control-structures/index.qmd
        - part2-control-structures/ch03-conditionals.qmd
    - references.qmd

format:
  html:
    theme: cosmo
    toc: true               # Table of contents for each page
    code-copy: true         # Handy "Copy" button on Go code snippets
  pdf:
    documentclass: scrreprt # Excellent for academic printing
